name = "TCIITensorConversion"
uuid = "9f0aa9f4-9415-4e6a-8795-331ebf40aa04"
authors = ["Ritter.Marc <Ritter.Marc@physik.uni-muenchen.de> and contributors"]
version = "0.1.4"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"

[compat]
ITensors = "0.7"
Reexport = "1.2.2"
TensorCrossInterpolation = "0.8, 0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
